spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3307/authService
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: verysecret
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  docker:
    compose:
      lifecycle-management: start-only